apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-blue
  namespace: hello-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
      variant: blue
  template:
    metadata:
      labels:
        app: hello-kubernetes
        variant: blue
    spec:
      containers:
        - name: web-server
          image: hello-k8s-web
          imagePullPolicy: Never
          args: ["blue"]
          ports:
            - containerPort: 80
