apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
      variant: green
  template:
    metadata:
      labels:
        app: hello-kubernetes
        variant: green
    spec:
      containers:
        - name: web-server
          image: hello-k8s-web
          imagePullPolicy: Never
          args: ["green"]
          ports:
            - containerPort: 80
