apiVersion: v1
kind: Service
metadata:
  # OrbStack: http://hello-k8s-green.default.svc.cluster.local:8080
  name: hello-k8s-green
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
    variant: green
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30081
