apiVersion: v1
kind: Service
metadata:
  # OrbStack: http://web-green.demo.svc.cluster.local:8080
  name: web-green
spec:
  type: NodePort
  selector:
    app: web
    variant: green
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30081
