apiVersion: v1
kind: Service
metadata:
  # OrbStack 環境ではこの name がそのまま DNS になる
  # → http://hello-k8s-service.default.svc.cluster.local でアクセス可能
  name: hello-k8s-service
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
